# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6b53cc3b361a16bccca73c83fc15ca822662195b1a80cf0d21919c790840cc55ebc92b30c3479f32b4b3612a2a95367b34f42221ee1bdcf073906e71ae418410

test:
  secret_key_base: 88d869300f0c9d9f2961e25d5de145ceb78b14305081e8c6118b6b01546d4a5a5d198f35faaf4c7434ffb1027c589845da5410da9c299646981e1f3ce6c2f178

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
